name: Deploy Bakery Site to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Agar S3 bucket Mumbai mein hai to ye rakhein

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://shukla-bakery-work --delete --exclude ".git/*" --exclude ".github/*"
        # ⚠️ Upar 'YOUR-BUCKET-NAME' ko apne S3 bucket ke asli naam se badal dena

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"